# Title of the workflow
name: Moodle Plugin CI

on:
  - workflow_dispatch
  - push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Virtual environment to use.
    runs-on: ubuntu-latest

    # DB services you need for testing.
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: 'root'
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    # Determines build matrix. This is a list of PHP versions, databases and
    # branches to test our project against. For each combination a separate
    # build will be created. For example below 6 builds will be created in
    # total (7.4-pgsql, 7.4-mariadb, 8.0-pgsql, 8.0-mariadb, etc.). If we add
    # another branch, total number of builds will become 12.
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3']
        moodle-branch: ['MDL-83541_main']
        database: [pgsql]

    # There is an alternative way allowing to define explicitly define which php, moodle-branch
    # and database to use:
    #
    # matrix:
    #   include:
    #     - php: '8.0'
    #       moodle-branch: 'MOODLE_401_STABLE'
    #       database: pgsql
    #     - php: '8.0'
    #       moodle-branch: 'MOODLE_400_STABLE'
    #       database: mariadb
    #     - php: '7.4'
    #       moodle-branch: 'MOODLE_311_STABLE'
    #       database: pgsql

    steps:
      # Check out this repository code in ./plugin directory
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      # Install PHP of required version. For possible options see https://github.com/shivammathur/setup-php
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
          # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
          coverage: none

      # Install this project into a directory called "ci", updating PATH and
      # locale, define nvm location.
      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
          sudo locale-gen en_AU.UTF-8
          echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

      # Run the default install.
      # Optionally, it is possible to specify a different Moodle repo to use
      # (https://github.com/moodle/moodle.git is used by default) and define
      # ignore directives or any other env vars for install step.  For more
      # details on configuring for specific requirements please refer to the
      # 'Help' page.
      #
      # env:
      #   MOODLE_REPO=https://github.com/username/moodle.git
      #   IGNORE_PATHS: 'ignore'
      #   IGNORE_NAMES: 'ignore_name.php'
      #   MUSTACHE_IGNORE_NAMES: 'broken.mustache'
      #   CODECHECKER_IGNORE_PATHS: 'ignoreme'
      #   CODECHECKER_IGNORE_NAMES: 'ignoreme_name.php'
      #
      # Other env vars are available for install, namely:
      #   - DB_USER / DB_PASS / DB_NAME / DB_HOST / DB_PORT: used
      #     by install to feed the corresponding --db-xxxx options.
      #   - MOODLE_APP: used to install dependencies to run Behat tests
      #     using the Moodle App.
      - name: Install moodle-plugin-ci
        run: |
          moodle-plugin-ci add-plugin brissone/moodle-qtype_musictheory
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyoddname
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyofischer
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyolewis
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyomech
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyomechjs
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyoname
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyonamejs
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyonewman
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyoselect
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyoselectjs
          moodle-plugin-ci add-plugin cleblond/moodle-qtype_easyostructure
          moodle-plugin-ci add-plugin collins-construction/moodle-qtype_externaltask
          moodle-plugin-ci add-plugin dualcube/moodle-qtype_ddmatch
          moodle-plugin-ci add-plugin ecampbell/moodle-qtype_multichoiceset
          moodle-plugin-ci add-plugin elearning-ostfalia/moodle-qtype_proforma
          moodle-plugin-ci add-plugin ethz-let/moodle-qtype_drawing
          moodle-plugin-ci add-plugin ethz-let/moodle-qtype_freehanddrawing
          moodle-plugin-ci add-plugin ethz-let/moodle-qtype_kprime
          moodle-plugin-ci add-plugin ethz-let/moodle-qtype_lti
          moodle-plugin-ci add-plugin ethz-let/moodle-qtype_sc
          moodle-plugin-ci add-plugin ethz-let/moodle-qtype_mtf
          moodle-plugin-ci add-plugin FormulasQuestion/moodle-qtype_formulas
          moodle-plugin-ci add-plugin fredrikw/fwstructmatch
          moodle-plugin-ci add-plugin gbateson/moodle-qtype_essayautograde
          moodle-plugin-ci add-plugin --clone https://gricad-gitlab.univ-grenoble-alpes.fr/moodle-plugins/moodle-qtype_vplquestion
          moodle-plugin-ci add-plugin jayhuber/musicinterval
          moodle-plugin-ci add-plugin jayhuber/musickeysignature
          moodle-plugin-ci add-plugin jayhuber/musicscale
          moodle-plugin-ci add-plugin justinhunt/moodle-qtype_cloudpoodll
          moodle-plugin-ci add-plugin justinhunt/moodle-qtype_poodllrecording
          moodle-plugin-ci add-plugin KQMATH/moodle-qtype_shortmath
          moodle-plugin-ci add-plugin Laboratoire-de-Chemoinformatique/moodle-qtype_molsimilarity
          moodle-plugin-ci add-plugin Laboratoire-de-Chemoinformatique/moodle-qtype_reacsimilarity
          moodle-plugin-ci add-plugin Ladone/blocklymoodle
          moodle-plugin-ci add-plugin lechunche/type_calc_sheet
          moodle-plugin-ci add-plugin marcusgreen/moodle-qtype_gapfill
          moodle-plugin-ci add-plugin marcusgreen/moodle-qtype_wordselect
          moodle-plugin-ci add-plugin maths/moodle-qtype_stack
          moodle-plugin-ci add-plugin mebis-lp/moodle-qtype_geogebra
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_combined
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_crossword
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_gapselect
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_opaque
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_oumultiresponse
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_pmatch
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_pmatchjme
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_recordrtc
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_varnumeric
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_varnumericset
          moodle-plugin-ci add-plugin moodleou/moodle-qtype_varnumunit
          moodle-plugin-ci add-plugin ndunand/moodle-qtype_matrix
          moodle-plugin-ci add-plugin ndunand/moodle-qtype_multinumerical
          moodle-plugin-ci add-plugin nfreear/moodle-qtype_calculatedobjects
          moodle-plugin-ci add-plugin rezeau/moodle-qtype_answersselect
          moodle-plugin-ci add-plugin rezeau/moodle-qtype_multianswerrgx
          moodle-plugin-ci add-plugin rezeau/moodle-qtype_regexp
          moodle-plugin-ci add-plugin SN-RECIT-formation-a-distance/moodle-qtype_numericalrecit
          moodle-plugin-ci add-plugin StudiUM/moodle-qtype_tcs
          moodle-plugin-ci add-plugin StudiUM/moodle-qtype_tcsjudgment
          moodle-plugin-ci add-plugin timhunt/moodle-qtype_pmatchreverse
          moodle-plugin-ci add-plugin trampgeek/moodle-qtype_coderunner
          moodle-plugin-ci add-plugin tuttorsOfTheTUBerlin/javaunittest
          moodle-plugin-ci add-plugin --branch MOODLE_36_STABLE vfremaux/moodle-qtype_splitset
          moodle-plugin-ci add-plugin villalon/qtype_conceptmap
          moodle-plugin-ci add-plugin VIP-Research-Group/moodle-qtype_shortanssimilarity
          moodle-plugin-ci add-plugin vmsreeram/moodle-qtype_essayannotate
          moodle-plugin-ci add-plugin wiris/moodle-qtype_essaywiris
          moodle-plugin-ci add-plugin wiris/moodle-qtype_matchwiris
          moodle-plugin-ci add-plugin wiris/moodle-qtype_multianswerwiris
          moodle-plugin-ci add-plugin wiris/moodle-qtype_multichoicewiris
          moodle-plugin-ci add-plugin wiris/moodle-qtype_shortanswerwiris
          moodle-plugin-ci add-plugin wiris/moodle-qtype_truefalsewiris
          moodle-plugin-ci add-plugin wiris/moodle-qtype_wq
          moodle-plugin-ci add-plugin Wunderbyte-GmbH/moodle_qtype_jack
          mv ${GITHUB_WORKSPACE}/moodle-plugin-ci-plugins/moodle-qtype_numericalrecit/src/* ${GITHUB_WORKSPACE}/moodle-plugin-ci-plugins/moodle-qtype_numericalrecit
          moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1 --repo https://github.com/marxjohnson/moodle.git
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
          # Uncomment this to run Behat tests using the Moodle App.
          # MOODLE_APP: 'true'

      # Steps that are run for the purpose of testing.  Any of these steps
      # can be re-ordered or removed to your liking.  And of course, you can
      # add any of your own custom steps.
      - name: PHPUnit tests
        if: ${{ !cancelled() }}
        run: moodle-plugin-ci phpunit -c phpunit.xml

      - name: Mark cancelled jobs as failed.
        if: ${{ cancelled() }}
        run: exit 1
